services:
  golem-provider:
    build: .
    image: dognew/golem-node:latest
    container_name: golem_provider_node
    restart: unless-stopped
    environment:
      - GOLEM_LAUNCH_MODE=provider
      - GOLEM_PROVIDER_NAME=DogNew-Xeon-Node
    volumes:
      # Mapeia tudo. Nada se perde quando o container reiniciar.
      - ./golem-data/local:/root/.local
    devices:
      - "/dev/kvm:/dev/kvm"
    cpus: '12.0'
    mem_limit: 16g
    ports:
      - "40102:40102"
      - "7465:7465"
      - "11500:11500/udp"
